### ISSUE TITLE
中英文订阅是分离的？

### ISSUE THREAD

**Issue by Shitao5** [hongtaoh/hugo-ht#1]
个人挺喜欢 hugo-ht 这个主题的，后知后觉才发现居然是你自己设计的……先点个赞👍

我之前用 Feedly 订阅了你的网站（英文版），今天刷的时候发现没有中文版的内容，才发现中英文是独立的：

- <https://hongtaoh.com/en/blog/index.xml>
- <https://hongtaoh.com/cn/blog/index.xml>

不知是否是有意而为之，留一个 issue 提醒一下吧。

**Comment by hongtaoh** [comment]
哈哈，不能算是我自己设计的，我是在 hugo-xmin 基础上，加上参照别人的网站，一点点改的。

对，我是故意这样的，因为我的英文博客和中文博客面向的人不一样，所以就弄成了独立的订阅。

**Comment by Shitao5** [comment]
哈哈明白了，站在巨人的肩膀上😉
