### ISSUE TITLE
Why hugo-ht-new is created in installtion?

### ISSUE THREAD

**Issue by CyrusYip** [hongtaoh/hugo-ht#4]
```
mkdir hugo-ht-new
cp -r hugo-ht/* hugo-ht-new
rm -rf hugo-ht
mv hugo-ht-new hugo-ht
```

I don't understand why we need to put the source code to another directory and rename the directory into the original name. I think `git clone https://github.com/hongtaoh/hugo-ht` is enough.

**Comment by hongtaoh** [comment]
Haha. It's because I don't want to submodule. Or because I am not so fluent in Git. :(

**Comment by CyrusYip** [comment]
Do you want to get files, excluding the repository?

**Comment by hongtaoh** [comment]
> Do you want to get files, excluding the repository? If so, remove `.git` directory after cloning.
> 
> ```shell
> git clone https://github.com/hongtaoh/hugo-ht
> rm -rf hugo-ht/.git
> ```

Yes. That's what I wanted
